#### raw data overview & label mapping

In [1]:
import pandas as pd
import numpy as np

In [2]:
# load dataset
anno = pd.read_csv('../dataset/annofix-1year.csv',index_col=0)
edata = pd.read_csv('../dataset/final_TPM.csv',index_col=0)

In [3]:
anno

,sex,age,edu,end,GAF,RIN,raw_reads,clean_reads,Q20,Q30,...,SV8,SV9,SV10,SV11,NK,CC,virus,LP,sips,pscore
id,,,,,,,,,,,,,,,,,,,,,
n337,f,14,8,sym,56,8.1,7.911602,7.901730,97.24,92.79,...,-0.073186,0.005827,-0.000543,0.005647,0.004055,0.035119,0.066830,-0.013096,31,11
n342,m,17,9,sym,52,9.0,7.886186,7.877051,97.52,93.32,...,-0.066406,-0.157171,-0.035082,-0.040303,0.037363,0.037950,0.059188,-0.017488,34,4
n346,m,17,9,sym,47,8.8,7.936888,7.928224,97.39,93.09,...,-0.052265,0.031095,-0.020729,0.102335,-0.066530,-0.041567,0.264255,-0.012749,59,15
n348,m,21,14,sym,48,8.3,7.857012,7.849438,97.24,92.78,...,-0.029202,-0.046029,0.178503,0.077423,0.165338,0.266639,0.101687,-0.017096,34,0
n349,m,18,9,con,46,8.3,7.973639,7.963862,98.07,94.73,...,-0.195343,-0.068118,-0.058421,0.007673,-0.000585,-0.063100,-0.048688,0.104332,42,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
n442c,f,14,8,sym,66,8.8,7.989200,7.983345,97.68,93.76,...,0.101836,0.026601,0.030326,0.026787,0.086662,-0.007568,0.007942,-0.003893,21,6
n449c,m,15,9,re,72,7.9,7.994069,7.985102,97.71,93.89,...,0.084630,0.037432,-0.048947,-0.082435,0.002116,-0.047479,-0.019303,-0.008848,15,2
n457c,f,27,16,sym,71,6.9,7.999861,7.991270,97.48,93.40,...,0.169584,0.073643,-0.097116,0.037249,0.090897,-0.018015,0.014526,-0.016906,25,7
n465c,f,14,8,sym,60,7.5,8.022328,8.013831,97.73,93.97,...,0.118327,0.055029,-0.010515,0.103375,-0.070144,-0.065045,-0.051938,-0.018346,38,6
n490c,m,16,7,sym,51,8.4,7.997217,7.988606,97.74,93.98,...,-0.013196,0.051053,0.095580,0.035752,-0.147858,0.009039,-0.166722,-0.025842,43,5

In [4]:
edata = edata.T
edata

,HBB,HBA2,HBA1,ACTB,MT-CO1,CSF3R,HLA-E,HLA-B,EEF1A1,HLA-C,...,RF00019,AC006380.1,AGR3,RHBDF1P1,GAPDHP67,SKOR2,AC007064.2,MAB21L4,AC006328.1,AL080248.1
n337,189139.77920,144329.63760,57333.19176,1511.450374,5369.776899,292.810180,1526.682301,948.217803,217.127680,2787.767863,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n342,163644.29580,85963.66975,19439.91226,796.319789,3054.298859,208.414814,1172.367183,874.843181,783.172517,1192.485186,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n346,203124.22680,202256.97900,59463.93255,1411.492178,3785.058194,282.299687,1860.193068,1488.609951,205.081941,1098.062723,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n348,87945.66397,84210.64240,40842.45225,1522.363266,6390.685307,254.859499,1952.143857,1669.137821,286.681267,1734.680792,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n349,241279.19840,193225.34230,99879.04903,1080.669744,4314.938100,244.827510,1200.765614,902.971688,230.836894,1498.916049,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
n442c,127968.55620,169198.06090,96012.73426,1810.685048,6638.480746,242.918363,1729.408822,2079.682778,499.927151,3005.578394,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n449c,161117.73980,291879.32060,132785.08250,1476.907360,6956.938838,118.085962,985.960330,898.682278,225.483689,1087.980795,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n457c,83212.43744,159430.15800,55906.40764,1881.206956,10907.975540,166.125429,1470.813735,1285.171343,468.972415,2389.639826,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n465c,172080.24220,281136.47550,137278.24280,1070.665252,4569.260501,175.183501,1066.086740,821.054080,287.794067,1204.491454,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n490c,206062.57770,430483.13350,133454.37810,718.499124,2724.235289,86.770244,773.865921,738.474175,88.000808,807.448390,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
merged = anno.join(edata)
merged

,sex,age,edu,end,GAF,RIN,raw_reads,clean_reads,Q20,Q30,...,RF00019,AC006380.1,AGR3,RHBDF1P1,GAPDHP67,SKOR2,AC007064.2,MAB21L4,AC006328.1,AL080248.1
id,,,,,,,,,,,,,,,,,,,,,
n337,f,14,8,sym,56,8.1,7.911602,7.901730,97.24,92.79,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n342,m,17,9,sym,52,9.0,7.886186,7.877051,97.52,93.32,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n346,m,17,9,sym,47,8.8,7.936888,7.928224,97.39,93.09,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n348,m,21,14,sym,48,8.3,7.857012,7.849438,97.24,92.78,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n349,m,18,9,con,46,8.3,7.973639,7.963862,98.07,94.73,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
n442c,f,14,8,sym,66,8.8,7.989200,7.983345,97.68,93.76,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n449c,m,15,9,re,72,7.9,7.994069,7.985102,97.71,93.89,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n457c,f,27,16,sym,71,6.9,7.999861,7.991270,97.48,93.40,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n465c,f,14,8,sym,60,7.5,8.022328,8.013831,97.73,93.97,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n490c,m,16,7,sym,51,8.4,7.997217,7.988606,97.74,93.98,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
merged = merged.loc[:, ~merged.columns.duplicated()]

print(merged)
merged.to_pickle('../dataset/merged_data.pkl')

      sex  age  edu  end  GAF  RIN  raw_reads  clean_reads    Q20    Q30  ...  \
id                                                                        ...
n337    f   14    8  sym   56  8.1   7.911602     7.901730  97.24  92.79  ...
n342    m   17    9  sym   52  9.0   7.886186     7.877051  97.52  93.32  ...
n346    m   17    9  sym   47  8.8   7.936888     7.928224  97.39  93.09  ...
n348    m   21   14  sym   48  8.3   7.857012     7.849438  97.24  92.78  ...
n349    m   18    9  con   46  8.3   7.973639     7.963862  98.07  94.73  ...
...    ..  ...  ...  ...  ...  ...        ...          ...    ...    ...  ...
n442c   f   14    8  sym   66  8.8   7.989200     7.983345  97.68  93.76  ...
n449c   m   15    9   re   72  7.9   7.994069     7.985102  97.71  93.89  ...
n457c   f   27   16  sym   71  6.9   7.999861     7.991270  97.48  93.40  ...
n465c   f   14    8  sym   60  7.5   8.022328     8.013831  97.73  93.97  ...
n490c   m   16    7  sym   51  8.4   7.997217     7.988606  97.74  93.98  ...

       EEF1A1P21  AC006380.1  AGR3  RHBDF1P1  GAPDHP67  SKOR2  AC007064.2  \
id
n337    0.000000         0.0   0.0       0.0       0.0    0.0         0.0
n342    0.000000         0.0   0.0       0.0       0.0    0.0         0.0
n346    0.000000         0.0   0.0       0.0       0.0    0.0         0.0
n348    0.000000         0.0   0.0       0.0       0.0    0.0         0.0
n349    0.000000         0.0   0.0       0.0       0.0    0.0         0.0
...          ...         ...   ...       ...       ...    ...         ...
n442c   0.000000         0.0   0.0       0.0       0.0    0.0         0.0
n449c   0.000000         0.0   0.0       0.0       0.0    0.0         0.0
n457c   0.000000         0.0   0.0       0.0       0.0    0.0         0.0
n465c   0.041761         0.0   0.0       0.0       0.0    0.0         0.0
n490c   0.000000         0.0   0.0       0.0       0.0    0.0         0.0

       MAB21L4  AC006328.1  AL080248.1
id
n337       0.0         0.0         0.0
n342       0.0         0.0         0.0
n346       0.0         0.0         0.0
n348       0.0         0.0         0.0
n349       0.0         0.0         0.0
...        ...         ...         ...
n442c      0.0         0.0         0.0
n449c      0.0         0.0         0.0
n457c      0.0         0.0         0.0
n465c      0.0         0.0         0.0
n490c      0.0         0.0         0.0

[107 rows x 39528 columns]

In [7]:
merged = pd.read_pickle('../dataset/merged_data.pkl')
merged.replace('f', 1, inplace=True)
merged.replace('m', 0, inplace=True)
merged.replace('re', 0, inplace=True)
merged.replace('sym', 0, inplace=True)
merged.replace('con', 1, inplace=True)
merged

,sex,age,edu,end,GAF,RIN,raw_reads,clean_reads,Q20,Q30,...,EEF1A1P21,AC006380.1,AGR3,RHBDF1P1,GAPDHP67,SKOR2,AC007064.2,MAB21L4,AC006328.1,AL080248.1
id,,,,,,,,,,,,,,,,,,,,,
n337,1,14,8,0,56,8.1,7.911602,7.901730,97.24,92.79,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n342,0,17,9,0,52,9.0,7.886186,7.877051,97.52,93.32,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n346,0,17,9,0,47,8.8,7.936888,7.928224,97.39,93.09,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n348,0,21,14,0,48,8.3,7.857012,7.849438,97.24,92.78,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n349,0,18,9,1,46,8.3,7.973639,7.963862,98.07,94.73,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
n442c,1,14,8,0,66,8.8,7.989200,7.983345,97.68,93.76,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n449c,0,15,9,0,72,7.9,7.994069,7.985102,97.71,93.89,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n457c,1,27,16,0,71,6.9,7.999861,7.991270,97.48,93.40,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n465c,1,14,8,0,60,7.5,8.022328,8.013831,97.73,93.97,...,0.041761,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n490c,0,16,7,0,51,8.4,7.997217,7.988606,97.74,93.98,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
label = np.array(merged['end'])
label

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [9]:
merged.to_pickle('../dataset/merged_data_2class.pkl')

In [10]:
merged = pd.read_pickle('../dataset/merged_data.pkl')
merged.replace('f', 1, inplace=True)
merged.replace('m', 0, inplace=True)
merged.replace('re', 0, inplace=True)
merged.replace('sym', 1, inplace=True)
merged.replace('con', 2, inplace=True)
merged

,sex,age,edu,end,GAF,RIN,raw_reads,clean_reads,Q20,Q30,...,EEF1A1P21,AC006380.1,AGR3,RHBDF1P1,GAPDHP67,SKOR2,AC007064.2,MAB21L4,AC006328.1,AL080248.1
id,,,,,,,,,,,,,,,,,,,,,
n337,1,14,8,1,56,8.1,7.911602,7.901730,97.24,92.79,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n342,0,17,9,1,52,9.0,7.886186,7.877051,97.52,93.32,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n346,0,17,9,1,47,8.8,7.936888,7.928224,97.39,93.09,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n348,0,21,14,1,48,8.3,7.857012,7.849438,97.24,92.78,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n349,0,18,9,2,46,8.3,7.973639,7.963862,98.07,94.73,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
n442c,1,14,8,1,66,8.8,7.989200,7.983345,97.68,93.76,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n449c,0,15,9,0,72,7.9,7.994069,7.985102,97.71,93.89,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n457c,1,27,16,1,71,6.9,7.999861,7.991270,97.48,93.40,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n465c,1,14,8,1,60,7.5,8.022328,8.013831,97.73,93.97,...,0.041761,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n490c,0,16,7,1,51,8.4,7.997217,7.988606,97.74,93.98,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
merged.to_pickle('../dataset/merged_data_3class.pkl')

In [12]:
merged = pd.read_pickle('../dataset/merged_data.pkl')
#merged.to_csv('../dataset/merged_data.csv')
merged

,sex,age,edu,end,GAF,RIN,raw_reads,clean_reads,Q20,Q30,...,EEF1A1P21,AC006380.1,AGR3,RHBDF1P1,GAPDHP67,SKOR2,AC007064.2,MAB21L4,AC006328.1,AL080248.1
id,,,,,,,,,,,,,,,,,,,,,
n337,f,14,8,sym,56,8.1,7.911602,7.901730,97.24,92.79,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n342,m,17,9,sym,52,9.0,7.886186,7.877051,97.52,93.32,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n346,m,17,9,sym,47,8.8,7.936888,7.928224,97.39,93.09,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n348,m,21,14,sym,48,8.3,7.857012,7.849438,97.24,92.78,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n349,m,18,9,con,46,8.3,7.973639,7.963862,98.07,94.73,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
n442c,f,14,8,sym,66,8.8,7.989200,7.983345,97.68,93.76,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n449c,m,15,9,re,72,7.9,7.994069,7.985102,97.71,93.89,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n457c,f,27,16,sym,71,6.9,7.999861,7.991270,97.48,93.40,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n465c,f,14,8,sym,60,7.5,8.022328,8.013831,97.73,93.97,...,0.041761,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
n490c,m,16,7,sym,51,8.4,7.997217,7.988606,97.74,93.98,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
# 2-class
merged = pd.read_pickle('../dataset/merged_data.pkl')
merged.replace('f', 1, inplace=True)
merged.replace('m', 0, inplace=True)
merged.replace('re', 0, inplace=True)
merged.replace('sym', 0, inplace=True)
merged.replace('con', 1, inplace=True)

year1 = merged[~merged.index.str.contains('c')]
year2 = merged[merged.index.str.contains('c')]

year1.to_pickle('../dataset/year1_3class.pkl')
year1.to_pickle('../dataset/year2_3class.pkl')

In [14]:
# 3-class
merged = pd.read_pickle('../dataset/merged_data.pkl')
merged.replace('f', 1, inplace=True)
merged.replace('m', 0, inplace=True)
merged.replace('re', 0, inplace=True)
merged.replace('sym', 1, inplace=True)
merged.replace('con', 2, inplace=True)

year1 = merged[~merged.index.str.contains('c')]
year2 = merged[merged.index.str.contains('c')]

year1.to_pickle('../dataset/year1_3class.pkl')
year1.to_pickle('../dataset/year2_3class.pkl')

In [15]:
merged = pd.read_pickle('../dataset/merged_data.pkl')
merged.to_csv('../dataset/merged_data.csv')